version: 0.0
os: linux
files:
  - source: /
    destination: /home/ubuntu/Cogether

hooks:
  ApplicationStop:
    - location: scripts/stop.sh
      runas: root
  BeforeInstall:
    - location: scripts/beforeInstall.bash
  AfterInstall:
    - location: scripts/initialize.sh
      runas: root
  ApplicationStart:
    - location: scripts/start.sh
      runas: root
